---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/11 12:36
---


--os.execute('python3 run test.py')
function test()
    return 'hello'
end

--获取文件路